POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 1,
  "name": "Prakriti",
  "email": "prakriti@gmail.com"
}

###
GET http://localhost:8080/users

###
POST http://localhost:8080/users/bulk
Content-Type: application/json

[
  {
    "id": 1,
    "name": "Prakriti",
    "email": "prakriti@gmail.com"
  },
  {
    "id": 2,
    "name": "Rohit",
    "email": "rohit@gmail.com"
  }
]

###
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Anush"
}

###
PATCH http://localhost:8080/users/2
Content-Type: application/json

{
  "name": "Anushkaa"
}
